name: demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # SDK constraint is correct

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.4
  firebase_remote_config: ^5.4.2
  firebase_performance: ^0.10.1+4
  firebase_in_app_messaging: ^0.8.1+4
  firebase_app_check: ^0.3.2+4



  # Other packages
  
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  http: ^1.3.0
  image_picker: ^1.1.2
  convert: ^3.1.2
  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.2
  flutter_animate: ^4.5.2
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8 
  material_color_utilities: ^0.11.1
  vm_service: ^14.3.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  cached_network_image: ^3.3.0
  video_player: ^2.9.5
  intl: ^0.20.2
  path: ^1.8.3
  liquid_progress_indicator: ^0.4.0
  uuid: ^4.3.3
  logger: ^2.5.0
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.4.0
  file_picker: ^9.2.1
  font_awesome_flutter: ^10.4.0
  location: ^8.0.0
  google_maps_flutter: ^2.12.0
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "assets/1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/1024.png
    - assets/mpesa.png
    - assets/ecocash.png
    - images/water.jpg
    - images/water2.jpg
    - images/water3.jpg
    - .env
