// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNmYZF7Bp98p2pVIiN4k4hEi0udnb9a8Q',
    appId: '1:201555512766:web:13600b40dca527aecabdef',
    messagingSenderId: '201555512766',
    projectId: 'smart-water-metering-sys',
    authDomain: 'smart-water-metering-sys.firebaseapp.com',
    storageBucket: 'smart-water-metering-sys.firebasestorage.app',
    measurementId: 'G-LZKHHKK1TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKrjZl2esqmYnw6DNBon2DtfIU9JZLvHQ',
    appId: '1:201555512766:android:8c52f505d3ae0355cabdef',
    messagingSenderId: '201555512766',
    projectId: 'smart-water-metering-sys',
    storageBucket: 'smart-water-metering-sys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBciSax5oKFx9NDjo9FWjI_yTPksTc8u78',
    appId: '1:201555512766:ios:91c66fc2ac888f6ecabdef',
    messagingSenderId: '201555512766',
    projectId: 'smart-water-metering-sys',
    storageBucket: 'smart-water-metering-sys.firebasestorage.app',
    iosBundleId: 'com.example.smartWaterMeteringSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBciSax5oKFx9NDjo9FWjI_yTPksTc8u78',
    appId: '1:201555512766:ios:91c66fc2ac888f6ecabdef',
    messagingSenderId: '201555512766',
    projectId: 'smart-water-metering-sys',
    storageBucket: 'smart-water-metering-sys.firebasestorage.app',
    iosBundleId: 'com.example.smartWaterMeteringSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNmYZF7Bp98p2pVIiN4k4hEi0udnb9a8Q',
    appId: '1:201555512766:web:31d2f60612105140cabdef',
    messagingSenderId: '201555512766',
    projectId: 'smart-water-metering-sys',
    authDomain: 'smart-water-metering-sys.firebaseapp.com',
    storageBucket: 'smart-water-metering-sys.firebasestorage.app',
    measurementId: 'G-VQ5K8GBKH2',
  );

}